export enum Country {
    baghdad = 'Baghdad',
    mosul = 'Mosul',
    duhok = 'duhok',
    ninawa = 'ninawa',
    arbil = 'arbil',
    karkuk = 'karkuk',
    silimania = 'silimania',
    anbar = 'anbar',
    diala = 'diala',
    karbala = 'karbala',
    babel = 'babel',
    waset = 'waset',
    kadesea = 'kadesea',
    najaf = 'najaf',
    missan = 'missan',
    zekar = 'zekar',
    mathna = 'mathna',
    basra = 'basra',
    salahAldean = 'salahAldean'
}